#!/bin/bash

# Revision 1.0  2018/08/14 15:30:00 MDT

# This plugin gets the count of the Orphan PIDs (which are older than 24 hours)

# This one is started for specific "html5client" process on the Stichers. 
# When the threshold (10) met, Stitcher will go degraded and no sessions will be sent to it

# This is extendable as job name and threshold count are passed from the nrpe.cfg

USAGE="$(basename "$0") [-w|--warning]<process count> [-c|--critical]<process count> [-p|--process]<process name>"
THRESHOLD_USAGE="WARNING threshold must be less than CRITICAL: $(basename "$0") $*"

# print usage
if [[ $# -lt 6 ]]
then
	echo ""
	echo "Wrong Syntax: $(basename "$0") $*"
	echo ""
	echo "Usage: $USAGE"
	echo ""
	exit 4
fi
# read input
while [[ $# -gt 0 ]]
  do
        case "$1" in
               -w|--warning)
               shift
               warning=$1
        ;;	
	       -c|--critical)
               shift
               critical=$1
	;;
               -p|--process)
               shift
               process=$1
        ;;
        esac
        shift
  done

if [[ $warning -eq $critical || $warning -gt $critical ]]
then
	echo ""
	echo "$THRESHOLD_USAGE"
	echo ""
        echo "Usage: $USAGE"
	echo ""
        exit 0
fi

# Orphan PIDs (which are older than 24 hours)
orphan=$(ps -eo start,pid,etime,cmd | grep -i "$process" | grep -v "^[0-9]" | wc -l)

if [[ "$(echo "$orphan >=  $critical"|bc)" -eq 1 ]]
	then
		echo "CRITICAL - Orphan PIDs are $orphan."
		exit 2
fi
if [[ "$(echo "$orphan >=  $warning"|bc)" -eq 1 ]]
        then
                echo "WARNING - Orphan PIDs are $orphan."
                exit 1
fi
if [[ "$(echo "$orphan <  $warning"|bc)" -eq 1 ]]
        then
		echo "OK - Orphan PIDs are $orphan."
		exit 0
fi
