#!/bin/bash
# Usage: ./script <expected_return_code> <url>

if [ $# -lt 2 ]; then
  echo "ERR: Invalid number of arguments provided to check script"
  exit 2
fi

return_code=$1
url=$2

return_value=$(curl -sL --connect-timeout 5 --max-time 8 "$url")
if [ "$return_value" == "$return_code" ];
then
  echo "OK: Artifactory health is OK"
  exit 0
else
  echo "Critical: Artifactory health is not OK"
  exit 2
fi
