#!/bin/bash

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
flag=0

hostname=$(hostname)

listVar="aabfl   albny   alcotn  allnmi  ashenc  augme   austx   bakca   baysmi  bhmal   birmal  bknny   bngny   bufny   canoh   clboh   cleoh   cscsc   daltx   delfl   denttx  detmi   ftwrtx  grdca   gsaasc  gsonc   gwinga  hvnny   hwdca   indin   ineca   jacktn  kearne  kennwa  kscmo   leedal  lncne   medfor  mkewi   mpkhca  mpksca  newnga  newtct  nmnny   ocfca   porme   qunny   ralnc   rchny   reddca  renonv  rochmn  rtxtx   saxtx   sdgca   sfvca   sldcmo  sldlla  slotca  smnny   spngtx  stckga  stclmn  stiny   stiny   syrny   tbdxla  tbdxla  tpbfl   tpffl   trictn  wilnc   worcma"

for i in $listVar; do
        if [[ "$hostname" = *"$i"* ]]
        then
                flag=1
		break
        fi
done

if [ $flag -eq 1 ]
then
        votoolsip="98.8.170.155"
else
        votoolsip="98.9.230.155"
fi

tsb_status=( $(curl -sL --connect-timeout 58 --max-time 59 http://$votoolsip:80/api/v1/tsb/clli/$(uname -n | awk -F"-" '{print $1}' | cut -c 6- ) | awk -F'"' '$2=="state"{print $4}'| head -n2) )
if [ ${#tsb_status[@]} -eq 0 ]; then
 echo "Unknown response"
 exit $STATE_WARNING
fi
if [ ${#tsb_status[@]} -ne 0 ]; then
  if [ "${tsb_status[0]}" != "null" -a "${tsb_status[1]}" != "null" ]; then
    if [ "${tsb_status[0]}" = "${tsb_status[1]}" ]; then
      if [ "${tsb_status[0]}" = "Running" ]; then
        echo "Service Critical: Both TSBroadcasters are Running"
        exit $STATE_CRITICAL
        elif [ "${tsb_status[0]}" = "Standby" ]; then
          echo "Service Critical: Both TSBroadcasters are in Standby"
          exit $STATE_CRITICAL
          elif [ "${tsb_status[0]}" = "Unknown" ]; then
            echo "Service Critical: TSBroadcasters status Unknown"
            exit $STATE_CRITICAL
          fi
        else
          echo "Service OK: Only one TSBroadcaster is running"
          exit $STATE_OK
        fi
      else
      echo "Unable to fetch the information of TSBroadcasters"
      exit $STATE_WARNING
      fi
    else
        echo "Unable to get the status of TSBroadcasters"
        exit $STATE_WARNING
fi
